//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOAD_Main.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuocHop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuocHop()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public string id_ch { get; set; }
        public string ten_ch { get; set; }
        public string dia_diem { get; set; }
        public Nullable<System.DateTime> tg_batdau { get; set; }
        public Nullable<System.DateTime> tg_ketthuc { get; set; }
        public string id_host { get; set; }
        public Nullable<bool> loi_nhac { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
